# Brings up all OMERO nodes on _one_ host computer, but multiple containers

# Version 3 is the newest version of the Compose file format
version: "3"

# Define all the services: database, omero server, omero web
services:
  # Add nginx service
  nginx:
    image: nginx:alpine
    container_name: nginx-ssl
    networks:
      - omero
    ports:
      - "4080:4080"    # HTTP for omeroweb
      - "4443:4443"    # HTTPS for omeroweb
      - "3000:3000"    # HTTP for metabase
      - "3443:3443"    # HTTPS for metabase
    volumes:
      - "../nginx/nginx.conf:/etc/nginx/nginx.conf:ro" # TODO: Make sure to have SSL certs match the location in nginx.conf, and change the server URL in the nginx.conf
      - "/etc/letsencrypt/:/etc/letsencrypt:ro"   # TODO: Make sure to have SSL certs in this folder
    
  # Name of our database, referenced in omero_db_host
  database:
    # Define a prebuilt Postgres image with a version
    image: "postgres:16" # Upgrade existing postgres 11 to 16 via backup and restore
    # Define environment variables (user/pass here)
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # Define named network to communicate with other containers
    networks:
      - omero
    # Define named volumes to persist data on host after shutdown
    volumes:
      - "database:/var/lib/postgresql/data"

  database-biomero:
    image: "postgres:16-alpine"
    environment:
      POSTGRES_USER: ${BIOMERO_POSTGRES_USER}
      POSTGRES_DB: ${BIOMERO_POSTGRES_DB}
      POSTGRES_PASSWORD: ${BIOMERO_POSTGRES_PASSWORD}
    networks:
      - omero
    volumes:
      - "database-biomero:/var/lib/postgresql/data"

  # Name of our omero server, referenced in omero_master_host
  omeroserver:
    # This container uses the tag for the latest server release of OMERO 5
    # To upgrade to the next major release, increment the major version number
    image: "cellularimagingcf/omeroserver:${NL_BIOMERO_VERSION:-latest}"
    # Define environment variables for use in the container.
    # 'nodedescriptors' assigns roles to all the containers
    # 'omero_db_*' are same as in 'database' description.
    security_opt:
      - seccomp=unconfined
    ulimits:
      nproc: 2048
      stack: 16777216
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: ${POSTGRES_USER}
      CONFIG_omero_db_pass: ${POSTGRES_PASSWORD}
      CONFIG_omero_db_name: ${POSTGRES_DB}
      CONFIG_omero_server_nodedescriptors: >-
        master:Blitz-0
        omeroworker-1:Tables-0,Indexer-0,PixelData-0,DropBox,MonitorServer,FileServer,Storm
        biomeroworker:Processor-0
      CONFIG_omero_master_host: omeroserver
      CONFIG_omero_scripts_timeout: ${OMERO_SCRIPTS_TIMEOUT}
      CONFIG_omero_sessions_timeout: ${OMERO_SESSIONS_TIMEOUT}
      CONFIG_omero_logging_level: ${OMERO_LOGGING_LEVEL}
      ROOTPASS: ${OMERO_ROOT_PASSWORD}
    # Define named network to communicate with other containers
    networks:
      - omero
    # Map ports to ports on the host machine, to connect remotely
    ports:
      - "4063:4063"
      - "4064:4064"
    # Define named volume and map a folder from the host machine
    volumes:
      - "omero:/OMERO"
      - "../web/L-Drive:/data"

  # Name of our worker node, can be anything
  omeroworker-1:
    image: "cellularimagingcf/omeroworker:${NL_BIOMERO_VERSION:-latest}"
    # Define variables for use in the container.
    # WORKER_NAME is used in the omero/ice node description
    security_opt:
      - seccomp=unconfined
    ulimits:
      nproc: 2048
      stack: 16777216
    environment:
      CONFIG_omero_master_host: omeroserver
      OMERO_WORKER_NAME: omeroworker-1
      CONFIG_omero_scripts_timeout: ${OMERO_SCRIPTS_TIMEOUT}
    # Named network to communicate with other containers
    networks:
      - omero
    # Named volume to share data access and persist data
    volumes:
      - "omero:/OMERO"
      - "../web/L-Drive:/data"

  # Define our processor worker
  biomeroworker:
    image: "cellularimagingcf/biomero:${NL_BIOMERO_VERSION:-latest}"
    # Define variables for use in the container.
    # WORKER_NAME is used in the omero/ice node description
    # logging_level doesn't work, but should increase logging
    security_opt:
      - seccomp=unconfined
    ulimits:
      nproc: 2048
      stack: 16777216
    environment:
      CONFIG_omero_master_host: omeroserver
      OMERO_WORKER_NAME: biomeroworker
      CONFIG_omero_logging_level: ${OMERO_LOGGING_LEVEL}
      CONFIG_omero_sessions_timeout: ${OMERO_SESSIONS_TIMEOUT}
      CONFIG_omero_scripts_timeout: ${OMERO_SCRIPTS_TIMEOUT}
      PERSISTENCE_MODULE: eventsourcing_sqlalchemy
      SQLALCHEMY_URL: postgresql+psycopg2://${BIOMERO_POSTGRES_USER}:${BIOMERO_POSTGRES_PASSWORD}@database-biomero:5432/${BIOMERO_POSTGRES_DB}
      INGEST_TRACKING_DB_URL: postgresql+psycopg2://${BIOMERO_POSTGRES_USER}:${BIOMERO_POSTGRES_PASSWORD}@database-biomero:5432/${BIOMERO_POSTGRES_DB}
      IMPORTER_ENABLED: ${IMPORTER_ENABLED}
    # Named network to communicate with other containers
    networks:
      - omero
    # Named volume to share data access and persist data
    # Forward host SSH setup to container
    volumes:
      - "omero:/OMERO"
      - "/opt/omero/.ssh:/tmp/.ssh:ro" # TODO: Make sure to open permissions on the host e.g. chmod -R 777 /opt/omero/.ssh
      - "../web/slurm-config.ini:/opt/omero/server/slurm-config.ini:rw"
      - "../web/L-Drive:/data"
      - "../config/biomero-importer:/opt/omero/server/config-importer:ro"
      - "../web/biomero-config.json:/opt/omero/server/biomero-config.json:ro"

  # Service for the omero.web UI
  omeroweb:
    image: "cellularimagingcf/omeroweb:${NL_BIOMERO_VERSION:-latest}"
    # Environment variables for in the container
    # login__logo supplies a logo on the starting page of web UI
    security_opt:
      - seccomp=unconfined
    ulimits:
      nproc: 2048
      stack: 16777216
    environment:
      OMEROHOST: omeroserver
      ROOTPASS: ${OMERO_ROOT_PASSWORD}
      CONFIG_omero_web_login__logo: "https://cembo.eu/wp-content/uploads/2021/04/Amsterdam-UMC.png"
      CONFIG_omero_scripts_timeout: ${OMERO_SCRIPTS_TIMEOUT}
      CONFIG_omero_web_session__expire__at__browser__close: "${OMERO_WEB_SESSION_EXPIRE_AT_BROWSER_CLOSE}"
      CONFIG_omero_web_session__cookie__age: ${OMERO_WEB_SESSION_COOKIE_AGE}
      ENV: ${OMERO_WEB_ENV}
      OMERO_BIOMERO_CONFIG_FILE: /opt/omero/web/OMERO.web/var/biomero-config.json
      METABASE_SITE_URL: ${METABASE_SITE_URL}
      METABASE_SECRET_KEY: ${METABASE_SECRET_KEY}
      METABASE_IMPORTS_DB_PAGE_DASHBOARD_ID: ${METABASE_IMPORTS_DB_PAGE_DASHBOARD_ID}
      METABASE_WORKFLOWS_DB_PAGE_DASHBOARD_ID: ${METABASE_WORKFLOWS_DB_PAGE_DASHBOARD_ID}
      INGEST_TRACKING_DB_URL: postgresql+psycopg2://${BIOMERO_POSTGRES_USER}:${BIOMERO_POSTGRES_PASSWORD}@database-biomero:5432/${BIOMERO_POSTGRES_DB}
      IMPORT_MOUNT_PATH: ${IMPORT_MOUNT_PATH}
      FORMS_MASTER_USER: ${FORMS_MASTER_USER}
      FORMS_MASTER_PASSWORD: ${FORMS_MASTER_PASSWORD}
      IMPORTER_ENABLED: ${IMPORTER_ENABLED}
      ANALYZER_ENABLED: ${ANALYZER_ENABLED}
    # Named network to communicate with other containers
    networks:
      - omero
    # Map ports to ports on the host machine, to allow opening of webpage
    # Remove port section when we add nginx to do it
    #ports:
    #  - "4080:4080"
    volumes:
      - "../web/slurm-config.ini:/opt/omero/web/OMERO.web/var/slurm-config.ini:rw"
      - "../web/biomero-config.json:/opt/omero/web/OMERO.web/var/biomero-config.json:rw"
      - "../web/local_omeroweb_edits/pretty_login/login_page_images/bioimaging.png:/opt/omero/web/venv3/lib/python3.9/site-packages/omeroweb/webclient/static/webclient/image/login_page_images/AmsterdamUMC-logo.png:ro"
      - "../web/L-Drive:/data:rw"

  metabase:
    image: metabase/metabase@sha256:f7b5dc52c21aaa2dca910a450e7e6119a975090ce9fc80726aa0742882ca176c
    container_name: metabase
    hostname: metabase
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_USER: ${METABASE_USER}
      MB_PASSWORD: ${METABASE_PASSWORD}
    networks:
      - omero
    # Remove port section to let nginx handle it
    #ports:
    #  - "3000:3000"
    volumes:
      - "../metabase:/metabase-data"

  biomero-importer:
    image: "cellularimagingcf/biomero-importer:${BIOMERO_IMPORTER_VERSION:-latest}"
    privileged: true
    profiles:
      - "IMPORTER_ENABLED"
    devices:
      - "/dev/fuse:/dev/fuse"
    security_opt:
      - "label=disable"
    environment:
      OMERO_HOST: omeroserver
      OMERO_USER: ${OMERO_IMPORTER_USER}
      OMERO_PASSWORD: ${OMERO_ROOT_PASSWORD}
      OMERO_PORT: ${OMERO_PORT}
      INGEST_TRACKING_DB_URL: postgresql+psycopg2://${BIOMERO_POSTGRES_USER}:${BIOMERO_POSTGRES_PASSWORD}@database-biomero:5432/${BIOMERO_POSTGRES_DB}
      ADI_RUN_MIGRATIONS: ${ADI_RUN_MIGRATIONS}
      PODMAN_USERNS_MODE: keep-id
    networks:
      - omero
    volumes:
      - "omero:/OMERO"
      - "../web/L-Drive:/data" # TODO: Make sure to open permissions on the host e.g. chmod -R 777 ./web/L-Drive
      - "../config/biomero-importer:/auto-importer/config:ro"
      - "../logs/biomero-importer:/auto-importer/logs"
    user: "${OMERO_CONTAINER_USER}"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

# Define the network(s) to communicate between containers
networks:
  omero:

# Define the named volume(s) to persist data to the host computer
volumes:
  database:
  database-biomero:
  omero: